/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ActionVariant = {
    Shell: 'SHELL',
    ClaudeActionsMcp: 'CLAUDE_ACTIONS_MCP',
    ClaudeRepositoryMcp: 'CLAUDE_REPOSITORY_MCP',
    ClaudeProjectMcp: 'CLAUDE_PROJECT_MCP'
} as const;
export type ActionVariant = typeof ActionVariant[keyof typeof ActionVariant];

