/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ActionScope = {
    Global: 'GLOBAL',
    Repository: 'REPOSITORY'
} as const;
export type ActionScope = typeof ActionScope[keyof typeof ActionScope];

