/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActionScope } from './actionScope';
import { ActionVariant } from './actionVariant';


export interface ActionConfigurationDto { 
    id?: string;
    name?: string;
    description?: string;
    executeScript?: string;
    checkScript?: string;
    interactive?: boolean;
    variant?: ActionVariant;
    scope?: ActionScope;
    repositoryId?: string;
    environment?: { [key: string]: string; };
}
export namespace ActionConfigurationDto {
}


