/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const AgentMcpScope = {
    Actions: 'ACTIONS',
    Repository: 'REPOSITORY',
    Project: 'PROJECT'
} as const;
export type AgentMcpScope = typeof AgentMcpScope[keyof typeof AgentMcpScope];

