/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgentSessionSource } from './agentSessionSource';


export interface AgentSessionRefDto { 
    sessionId?: string;
    source?: AgentSessionSource;
    forkedFromSessionId?: string;
    transcriptPath?: string;
    recordedAt?: string;
}
export namespace AgentSessionRefDto {
}


