/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const AuditEntityType = {
    Epic: 'EPIC',
    Feature: 'FEATURE',
    Task: 'TASK'
} as const;
export type AuditEntityType = typeof AuditEntityType[keyof typeof AuditEntityType];

