/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Origin } from './origin';


export interface BootstrapCommandDto { 
    id?: string;
    name?: string;
    description?: string;
    executeScript?: string;
    checkScript?: string;
    orderIndex?: number;
    origin?: Origin;
    repositoryId?: string;
    environment?: { [key: string]: string; };
    createdAt?: string;
    updatedAt?: string;
}
export namespace BootstrapCommandDto {
}


