/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const CommandStatus = {
    Running: 'RUNNING',
    Exited: 'EXITED',
    Terminated: 'TERMINATED',
    Interrupted: 'INTERRUPTED'
} as const;
export type CommandStatus = typeof CommandStatus[keyof typeof CommandStatus];

