/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LogChannel } from './logChannel';


export interface CommandLogLineDto { 
    sequence?: number;
    channel?: LogChannel;
    content?: string;
    timestamp?: string;
}
export namespace CommandLogLineDto {
}


