/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommitFileChangeDto } from './commitFileChangeDto';


export interface CommitChangesDto { 
    commit?: string;
    parent?: string;
    files?: Array<CommitFileChangeDto>;
}

