/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommandKind } from './commandKind';
import { CommandStatus } from './commandStatus';


export interface CommandDto { 
    id?: string;
    repoId?: string;
    worktreeId?: string;
    branch?: string;
    commitHash?: string;
    shortCommitHash?: string;
    actionId?: string;
    actionName?: string;
    status?: CommandStatus;
    exitCode?: number;
    interactive?: boolean;
    kind?: CommandKind;
    launchedAt?: string;
    finishedAt?: string;
}
export namespace CommandDto {
}


