/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RestartPolicy } from './restartPolicy';
import { LogObserverInput } from './logObserverInput';
import { LogSourceInput } from './logSourceInput';


export interface CreateRepositoryDaemonRequest { 
    name: string;
    description?: string;
    startScript: string;
    readyPattern?: string;
    stopSignal?: string;
    restartPolicy?: RestartPolicy;
    maxRestarts?: number;
    otel?: boolean;
    httpPort?: number;
    environment?: { [key: string]: string; };
    observers?: Array<LogObserverInput>;
    sources?: Array<LogSourceInput>;
}
export namespace CreateRepositoryDaemonRequest {
}


