/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RestartPolicy } from './restartPolicy';
import { HealthCheckInput } from './healthCheckInput';
import { LogObserverInput } from './logObserverInput';
import { LogSourceInput } from './logSourceInput';
import { WebViewInput } from './webViewInput';


export interface CreateRepositoryDaemonRequest { 
    name: string;
    description?: string;
    startScript: string;
    readyPattern?: string;
    stopSignal?: string;
    restartPolicy?: RestartPolicy;
    autoStart?: boolean;
    maxRestarts?: number;
    otel?: boolean;
    webView?: WebViewInput;
    environment?: { [key: string]: string; };
    observers?: Array<LogObserverInput>;
    sources?: Array<LogSourceInput>;
    healthChecks?: Array<HealthCheckInput>;
}
export namespace CreateRepositoryDaemonRequest {
}


