/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateBootstrapCommandRequest { 
    name: string;
    description?: string;
    executeScript: string;
    checkScript?: string;
    environment?: { [key: string]: string; };
    orderIndex?: number;
}

