/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LogObserverDto } from './logObserverDto';
import { RestartPolicy } from './restartPolicy';
import { DaemonScope } from './daemonScope';


export interface DaemonConfigurationDto { 
    id?: string;
    name?: string;
    description?: string;
    startScript?: string;
    readyPattern?: string;
    stopSignal?: string;
    restartPolicy?: RestartPolicy;
    maxRestarts?: number;
    scope?: DaemonScope;
    repositoryId?: string;
    environment?: { [key: string]: string; };
    observers?: Array<LogObserverDto>;
}
export namespace DaemonConfigurationDto {
}


