/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DaemonStatus } from './daemonStatus';
import { DaemonEventKind } from './daemonEventKind';
import { DaemonEventSeverity } from './daemonEventSeverity';


export interface DaemonEventDto { 
    repoId?: string;
    worktreeId?: string;
    daemonId?: string;
    daemonName?: string;
    kind?: DaemonEventKind;
    severity?: DaemonEventSeverity;
    status?: DaemonStatus;
    summary?: string;
    logExcerpt?: string;
    commandId?: string;
    timestamp?: string;
}
export namespace DaemonEventDto {
}


