/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const DaemonEventKind = {
    StatusChanged: 'STATUS_CHANGED',
    ErrorDetected: 'ERROR_DETECTED'
} as const;
export type DaemonEventKind = typeof DaemonEventKind[keyof typeof DaemonEventKind];

