/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const DaemonStatus = {
    Starting: 'STARTING',
    Ready: 'READY',
    Degraded: 'DEGRADED',
    Restarting: 'RESTARTING',
    Crashed: 'CRASHED',
    Stopped: 'STOPPED'
} as const;
export type DaemonStatus = typeof DaemonStatus[keyof typeof DaemonStatus];

