/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeatureFlowPhaseStepDto } from './featureFlowPhaseStepDto';


export interface Entry7 { 
    featureFlowPhaseStep?: FeatureFlowPhaseStepDto;
}

