/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorktreeDto } from './worktreeDto';


export interface Entry9 { 
    worktree?: WorktreeDto;
}

