/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkspaceHistoryDto } from './workspaceHistoryDto';


export interface Entry13 { 
    workspace?: WorkspaceHistoryDto;
}

