/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BootstrapStepDto } from './bootstrapStepDto';
import { BootstrapRunDto } from './bootstrapRunDto';


export interface Entry { 
    step?: BootstrapStepDto;
    lastRun?: BootstrapRunDto;
}

