/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeatureFlowPhaseDto } from './featureFlowPhaseDto';


export interface Entry4 { 
    featureFlowPhase?: FeatureFlowPhaseDto;
}

