/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FeatureDto { 
    id?: string;
    epicId?: string;
    title?: string;
    description?: string;
    dependsOnFeatureId?: string;
    implementedOn?: string;
    createdAt?: string;
    updatedAt?: string;
}

