/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeatureFlowPhaseStepDto } from './featureFlowPhaseStepDto';


export interface FeatureFlowPhaseDto { 
    id?: string;
    name?: string;
    description?: string;
    orderIndex?: number;
    featureFlowConfigurationId?: string;
    parentPhaseId?: string;
    steps?: Array<FeatureFlowPhaseStepDto>;
    subPhases?: Array<FeatureFlowPhaseDto>;
}

