/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgentLaunchMode } from './agentLaunchMode';
import { AgentType } from './agentType';
import { AgentMcpScope } from './agentMcpScope';


export interface LaunchAgentRequest { 
    scope: AgentMcpScope;
    initialContext?: string;
    mode?: AgentLaunchMode;
    resumeSessionId?: string;
    fork?: boolean;
    deliverTaskPrompt?: boolean;
    agentType?: AgentType;
}
export namespace LaunchAgentRequest {
}


