/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const LogObserverKind = {
    Pattern: 'PATTERN',
    LogLevel: 'LOG_LEVEL'
} as const;
export type LogObserverKind = typeof LogObserverKind[keyof typeof LogObserverKind];

