/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const LogSeverity = {
    Info: 'INFO',
    Warning: 'WARNING',
    Error: 'ERROR'
} as const;
export type LogSeverity = typeof LogSeverity[keyof typeof LogSeverity];

