/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const Origin = {
    Ui: 'UI',
    Config: 'CONFIG'
} as const;
export type Origin = typeof Origin[keyof typeof Origin];

