/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const RepositoryArchetype = {
    Project: 'PROJECT',
    Service: 'SERVICE',
    Library: 'LIBRARY',
    Integration: 'INTEGRATION',
    Application: 'APPLICATION',
    ServiceTemplate: 'SERVICE_TEMPLATE',
    Fork: 'FORK'
} as const;
export type RepositoryArchetype = typeof RepositoryArchetype[keyof typeof RepositoryArchetype];

