/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TelemetryLogDto } from './telemetryLogDto';


export interface Response79 { 
    logs?: Array<TelemetryLogDto>;
}

