/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Entry7 } from './entry7';


export interface Response37 { 
    entries?: Array<Entry7>;
}

