/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Entry8 } from './entry8';


export interface Response45 { 
    entries?: Array<Entry8>;
}

