/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditEntryDto } from './auditEntryDto';


export interface Response95 { 
    entries?: Array<AuditEntryDto>;
}

