/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeatureFlowConfigurationDto } from './featureFlowConfigurationDto';


export interface Response21 { 
    featureFlowConfiguration?: FeatureFlowConfigurationDto;
}

