/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectDto } from './projectDto';
import { RepositoryDto } from './repositoryDto';


export interface Response46 { 
    project?: ProjectDto;
    wrapper?: RepositoryDto;
}

