/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TelemetrySpanDto } from './telemetrySpanDto';


export interface Response90 { 
    spans?: Array<TelemetrySpanDto>;
}

