/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DaemonEventDto } from './daemonEventDto';


export interface Response20 { 
    events?: Array<DaemonEventDto>;
}

