/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorktreeHistoryDetailDto } from './worktreeHistoryDetailDto';


export interface Response56 { 
    worktree?: WorktreeHistoryDetailDto;
}

