/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkspaceHistoryDetailDto } from './workspaceHistoryDetailDto';


export interface Response87 { 
    workspace?: WorkspaceHistoryDetailDto;
}

