/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const RestartPolicy = {
    Never: 'NEVER',
    OnFailure: 'ON_FAILURE',
    Always: 'ALWAYS'
} as const;
export type RestartPolicy = typeof RestartPolicy[keyof typeof RestartPolicy];

