/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RepositoryDaemonDto } from './repositoryDaemonDto';
import { HealthCheckStatusDto } from './healthCheckStatusDto';
import { ServiceStatus } from './serviceStatus';


export interface ServiceInstanceDto { 
    daemon?: RepositoryDaemonDto;
    status?: ServiceStatus;
    restartCount?: number;
    commandId?: string;
    proxyPath?: string;
    health?: Array<HealthCheckStatusDto>;
}
export namespace ServiceInstanceDto {
}


