/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServiceEventKind } from './serviceEventKind';
import { ServiceStatus } from './serviceStatus';
import { ServiceEventSeverity } from './serviceEventSeverity';


export interface ServiceEventDto { 
    repoId?: string;
    workspaceId?: string;
    serviceId?: string;
    serviceName?: string;
    kind?: ServiceEventKind;
    severity?: ServiceEventSeverity;
    status?: ServiceStatus;
    summary?: string;
    logExcerpt?: string;
    commandId?: string;
    source?: string;
    anchorFrom?: number;
    anchorTo?: number;
    sourceEpoch?: string;
    timestamp?: string;
}
export namespace ServiceEventDto {
}


