/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskDto { 
    id?: string;
    featureId?: string;
    repositoryId?: string;
    title?: string;
    description?: string;
    dependsOnTaskId?: string;
    implementedAt?: string;
    createdAt?: string;
    updatedAt?: string;
}

