/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TelemetrySpanDto } from './telemetrySpanDto';
import { TelemetryLogDto } from './telemetryLogDto';


export interface TelemetryErrorGroupDto { 
    traceId?: string;
    serviceName?: string;
    errorSpans?: Array<TelemetrySpanDto>;
    errorLogs?: Array<TelemetryLogDto>;
}

