/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TelemetryMetricDto { 
    name?: string;
    description?: string;
    unit?: string;
    type?: string;
    value?: number;
    epochNanos?: number;
    serviceName?: string;
    attributes?: { [key: string]: string; };
}

