/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActionType } from './actionType';


export interface UpdateFeatureFlowPhaseActionRequest { 
    actionType?: ActionType;
    sortOrder?: number;
    parallelGroup?: string;
}
export namespace UpdateFeatureFlowPhaseActionRequest {
}


