/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorktreeStatus } from './worktreeStatus';


export interface WorktreeHistoryDto { 
    id?: number;
    worktreeId?: string;
    parent?: string;
    status?: WorktreeStatus;
    createdAt?: string;
    resolvedAt?: string;
}
export namespace WorktreeHistoryDto {
}


