/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkspaceRuntimeStatus } from './workspaceRuntimeStatus';
import { WorkspaceStatus } from './workspaceStatus';


export interface WorkspaceDto { 
    workspaceId?: string;
    parent?: string;
    branch?: string;
    ahead?: number;
    behind?: number;
    conflictsWithParent?: boolean;
    status?: WorkspaceStatus;
    runtimeStatus?: WorkspaceRuntimeStatus;
    runtimeError?: string;
    clean?: boolean;
    preamble?: string;
    result?: string;
    resolvedAt?: string;
    daemonConnectedAt?: string;
    daemonVersion?: string;
    daemonBuildTime?: string;
}
export namespace WorkspaceDto {
}


