/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkspaceEventType } from './workspaceEventType';


export interface WorkspaceEventDto { 
    type?: WorkspaceEventType;
    branch?: string;
    parent?: string;
    target?: string;
    commit?: string;
    note?: string;
    at?: string;
}
export namespace WorkspaceEventDto {
}


