/**
 * service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorktreeStatus } from './worktreeStatus';
import { WorktreeRuntimeStatus } from './worktreeRuntimeStatus';


export interface WorktreeDto { 
    worktreeId?: string;
    parent?: string;
    branch?: string;
    ahead?: number;
    behind?: number;
    conflictsWithParent?: boolean;
    status?: WorktreeStatus;
    runtimeStatus?: WorktreeRuntimeStatus;
    runtimeError?: string;
    preamble?: string;
    result?: string;
    resolvedAt?: string;
}
export namespace WorktreeDto {
}


