/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PromptAttachmentSource } from './promptAttachmentSource';


export interface WorkspacePromptAttachmentDataDto { 
    id?: string;
    mimeType?: string;
    label?: string;
    source?: PromptAttachmentSource;
    createdAt?: string;
    dataBase64?: string;
}
export namespace WorkspacePromptAttachmentDataDto {
}


