/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkspacePromptDraftDto { 
    content?: string;
    serializedPrompt?: string;
    promptVersion?: number;
    lastRunAt?: string;
    lastRunPromptVersion?: number;
    lastRunCommandId?: string;
    updatedAt?: string;
}

