/**
 * qits API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkspaceEventDto } from './workspaceEventDto';
import { CommandDto } from './commandDto';
import { WorkspaceStatus } from './workspaceStatus';


export interface WorkspaceHistoryDetailDto { 
    id?: number;
    workspaceId?: string;
    parent?: string;
    status?: WorkspaceStatus;
    preamble?: string;
    result?: string;
    createdAt?: string;
    resolvedAt?: string;
    events?: Array<WorkspaceEventDto>;
    commands?: Array<CommandDto>;
}
export namespace WorkspaceHistoryDetailDto {
}


